Repository Miller-GS/MC426A-TV-Application, pull requests merged in 2023-06, with the labels that each got.

#28 [Feat/6] Refactor authentication and logout
  api/.env.example
  api/app.ts
  api/environment.ts
  api/package.json
  api/src/controllers/users.ts
  api/src/entity/user.entity.ts
  api/src/middleware/auth.ts
  api/src/routes/users.ts
  api/src/utils/validationUtils.ts
  api/tests/controllers/users.test.ts
  api/tests/middleware/auth.test.ts
  api/tests/utils/validationUtils.test.ts
Labels: AvaliacaoA2

#32 Add C4 architecture to README
  README.md
  docs/images/architecture_c4.png
Labels: AvaliacaoA4.1

#46 Feat/39: Create Notifications on comment reply
  api/src/errors/EmptyNotificationError.ts
  api/src/errors/UserIdError.ts
  api/src/models/notification.ts
  api/src/routes/comment.ts
  api/src/services/commentService.ts
  api/src/services/notificationCreationService.ts
  api/src/services/replyNotification.ts
  api/tests/controllers/notification.test.ts
  api/tests/models/notification.test.ts
  api/tests/services/commentService.test.ts
  api/tests/services/notificationCreationService.test.ts
Labels: AvaliacaoA4.1

#48 Refact/47: Merge ConvertionUtils
  api/src/controllers/media.ts
  api/src/controllers/notification.ts
  api/src/utils/convertionUtils.ts
  api/src/utils/parseUtils.ts
  api/tests/utils/convertionUtils.test.ts
  api/tests/utils/parseUtils.test.ts
Labels: AvaliacaoA4.2

#49 Refact/47: Separate User controller and service
  api/app.ts
  api/src/controllers/comment.ts
  api/src/controllers/user.ts
  api/src/controllers/users.ts
  api/src/errors/InvalidAccessError.ts
  api/src/errors/InvalidRefreshTokenError.ts
  api/src/errors/UserAlreadyExistsError.ts
  api/src/errors/UserNotExistsError.ts
  api/src/routes/user.ts
  api/src/routes/users.ts
  api/src/services/userService.ts
  api/src/utils/errorUtils.ts
  api/tests/controllers/user.test.ts
  api/tests/controllers/users.test.ts
  api/tests/services/userService.test.ts
Labels: AvaliacaoA4.2
